name: contracts-test
on:
  push:
    paths:
      - 'contracts/**'
    branches:
      - main
  pull_request:
    paths:
      - 'contracts/**'
    branches:
      - main
jobs:
  hardhat-test:
    runs-on: ubuntu-latest
    container: node:lts
    services:
      sapphire-local-ci:
        image: ghcr.io/oasisprotocol/sapphire-dev:latest
        ports:
          - 8545
          - 8546
        env:
          OASIS_DEPOSIT: /oasis-deposit -to 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
        options: >-
          --rm
          --health-cmd="/oasis-node debug control wait-ready -a unix:/serverdir/node/net-runner/network/client-0/internal.sock"
          --health-start-period=90s
    steps:
      - name: install pnpm
        run: npm install -g pnpm
      - name: Checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: contracts
      - name: hardhat test
        run: pnpm hardhat test --network sapphire_local_ci
        working-directory: contracts
